apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: count
    value: "1"
  - name: failureLimit
    value: "1"
  - name: preview-service
  - name: interval
  metrics:
  - name: success-rate
    count: "{{ args.count }}"
    interval: "{{ args.interval }}"
    failureLimit: "{{ args.failureLimit }}"
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: >+
          sum(
            rate(nginx_ingress_controller_requests{ingress="{{ args.preview-service }}",status!~"[4-5].*"}[1m]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress="{{ args.preview-service }}"}[1m])
          )
